name: portal_cidadao
description: "Portal Cidadão - Fiscalização e transparência pública via dados da Câmara dos Deputados"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Rede / consumo de API
  dio: ^5.4.3

  # Persistência local (Favoritos offline)
  sqflite: ^2.3.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
