services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP (aplicação)
      - "15672:15672" # Management UI (http://localhost:15672 - guest/guest)
